# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.

{
    'name': "Loza Accounting",
    'version': "14.0.0.0",
    'currency': 'LYD',
    'summary': "Loza Accounting Module",
    'category': "productivity",
    'sequence': "10",
    'description': """
Loza Accounting Module for Libyan Enterprise
""",

    'depends': ['account'],
    'data': ['data/sequence.xml',
        'data/activity.xml',
        # 'data/journals.xml',
        'security/groups.xml',
        'reports/report_bank_notification.xml',
        'reports/report_payment.xml',
        'reports/report_reciept.xml',
        'views/res_company.xml',
        'views/loza_payment_approval.xml',
        'views/loza_reciept_approval.xml',
        'views/loza_bank_notification.xml',
        'views/loza_transaction_attachment.xml',
        'views/transaction_cash_payment.xml',
        'views/transaction_check_payment.xml',
        'views/transaction_cash_reciept.xml',
        'views/transaction_bank_notification.xml',
        'views/transaction_check_reciept.xml',
        'views/transaction_wire.xml',
        'views/account_payment.xml',
        'views/loza_loan.xml',
        'views/loza_pitty_cash.xml',
        'views/menu_items.xml',
        'security/ir.model.access.csv',
    ],
    'author': "Loza Inc",
    'website': "",
    'installable': True,
    'application': True,
    'auto_install': False,
}
